name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - mc: '1.21.4'
            yarn: '1.21.4+build.8'
            fapi: '0.119.2+1.21.4'
          - mc: '1.21.5'
            yarn: '1.21.5+build.1'
            fapi: '0.119.2+1.21.5'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      
      - name: Build
        run: ./gradlew build -Pminecraft_version=${{ matrix.mc }} -Pyarn_mappings=${{ matrix.yarn }} -Pfabric_version=${{ matrix.fapi }} -Parchives_base_name=wayfindr-mc${{ matrix.mc }}
      
      - name: Upload artifacts (mc ${{ matrix.mc }})
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-mc${{ matrix.mc }}
          path: build/libs/

  release:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Wayfindr-v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            artifacts/Artifacts-mc1.21.4/*.jar
            artifacts/Artifacts-mc1.21.5/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
