name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on tags that start with 'v', e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Wayfindr-v${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            build/libs/*.jar
